### ISSUE TITLE
Package is missing the lib/ folder

### ISSUE THREAD

**Issue by florianpnn** [xuopled/react-responsive-masonry#1]
I get an error when compiling with this package.
```
Error in ./src/App.js
Module not found: 'react-responsive-masonry' in ./.
```

After looking around I noticed that `main` in `package.json` is pointing toward nothing.
I ran the build script to get the `lib/` folder and now it's working fine.

**Comment by xuopled** [comment]
Hi, thank you for reporting this bug. Actually, I don't understand why the lib folder is missing.
With these two npm scripts, it should work right ?

```
"build": "babel ./src --out-dir ./lib --source-maps -d ./lib",
"prepublish": "yarn run clean && yarn run build",
```

**Comment by xuopled** [comment]
@florianpnn it should be good with the release `1.2.2` !
Sorry for the delay
