### ISSUE TITLE
doesn't work with server-side rendering

### ISSUE THREAD

**Issue by edoroshenko** [xuopled/react-responsive-masonry#9]
It relies on React hook `componentDidMount` and that is never being called on server.

**Comment by edoroshenko** [comment]
#10

**Comment by edoroshenko** [comment]
Created #10 with fix & tests

**Comment by xuopled** [comment]
@edoroshenko Thank you for reporting and fixing this. I put some comments on your PR

**Comment by xuopled** [comment]
I merged. Thank you. I will publish a new version

**Comment by xuopled** [comment]
Please checkout the v1.5.0
